# Simple workflow for deploying static content to GitHub Pages
name: Build pages when JSON uploaded

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - app/data/character-json.json

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.5
               
      - name: Go Get
        run: go get -d .
        working-directory : ./app
      - name: Run App
        run: go run .
        working-directory : ./app
        
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
    