name: TMB Data Pull

on: 
   workflow_dispatch:
   schedule:
     - cron: "0 0 * * 1,5"

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Verify dependencies
        run: go mod verify ./tmb-puller
        
      - name: Run Puller
        run: go run ./tmb-puller

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
