name: TMB Data Pull

on: 
   workflow_dispatch:
   schedule:
     - cron: "0 0 * * 1,5"

jobs:
  format-code:
    runs-on: windows-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository
      
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
               
      - run: go get -d .
        working-directory : ./tmb-puller
      - name: Run Puller
        run: go run .
        working-directory : ./tmb-puller
        env:
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
          DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
