# Simple workflow for deploying static content to GitHub Pages
name: Deploy pages when docs folder updated

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
                
      - run: go get -d .
        working-directory : ./tmb-puller
      - name: Run Puller
        run: go run .
        working-directory : ./tmb-puller
        env:
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
          DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}
      - name: Archive Failure Screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: ./tmb-puller/screenshots/failure.jpg
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
